baseURL = "https://hawc2.github.io/tu-collections-as-data/"
languageCode = "en-us"
title = "Collections as Data | Temple Libraries"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params]
  description = "A Collections as Data approach to Temple University Libraries' digital collections, visualizing and exploring materials through IIIF."
