baseURL = "https://hawc2.github.io/tu-digital-collections/"
languageCode = "en-us"
title = "Temple University Libraries Digital Collections"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params]
  description = "Explore the unique primary historical and cultural resources held by Temple University Libraries, served through the IIIF Image API."
